.gitignore
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/PropertyUtils.java
ccd-gradle-plugin/build.gradle
ccd-gradle-plugin/src/main/resources/application.properties
ccd-sdk-types/build.gradle
ccd-sdk-types/src/main/java/uk/gov/hmcts/ccd/sdk/types/Field.java

Remove ccd-sdk-types lib dependency on jackson annotations.

Remove types jackson dependency

---

.github/workflows/gradle.yml
ccd-gradle-plugin/build.gradle

Publish plugin to Gradle portal

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/Main.java
ccd-config-generator/src/test/java/uk/gov/hmcts/ccd/sdk/FPLConfigGenerationTests.java
ccd-config-generator/src/test/java/uk/gov/hmcts/ccd/sdk/UnitTest.java
ccd-config-generator/src/test/java/uk/gov/hmcts/example/missingcomplex/Applicant.java
ccd-config-generator/src/test/java/uk/gov/hmcts/example/missingcomplex/MissingComplex.java

Fix complex types not being exported

Fix complex types not being exported

---

gradle/wrapper/gradle-wrapper.properties

upgrade gradle to 6.2.2

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/CaseFieldGenerator.java
ccd-config-generator/src/test/java/uk/gov/hmcts/ccd/sdk/generator/CaseFieldGeneratorTest.java

As in title - fix for CCD data type problem.

Maps numeric values to appropriate Number CCD type

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigBuilderImpl.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/JsonUtils.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/CaseTypeTabGenerator.java
ccd-config-generator/src/test/java/uk/gov/hmcts/ccd/sdk/FPLConfigGenerationTests.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-cafcass.json
ccd-config-generator/src/test/resources/ccd-definition/CaseTypeTab.json
ccd-sdk-types/src/main/java/uk/gov/hmcts/ccd/sdk/types/BaseCCDConfig.java
ccd-sdk-types/src/main/java/uk/gov/hmcts/ccd/sdk/types/ConfigBuilder.java
ccd-sdk-types/src/main/java/uk/gov/hmcts/ccd/sdk/types/Tab.java
ccd-sdk-types/src/main/java/uk/gov/hmcts/ccd/sdk/types/TabField.java

Generation of CaseTypeTab json

Generation of CaseTypeTab json

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/AuthorisationCaseStateGenerator.java
ccd-config-generator/src/test/java/uk/gov/hmcts/ccd/sdk/FPLConfigGenerationTests.java
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseState.json

Generate AuthorisationCaseState

Generate AuthorisationCaseState

---

ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-sdk-types/src/main/java/uk/gov/hmcts/ccd/sdk/types/WorkBasket.java

new builder methods for workbasket state, caseId and created date fields

feat: implemented new builder methods for ccd metadata fields

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ResolvedCCDConfig.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/AuthorisationCaseTypeGenerator.java
ccd-config-generator/src/test/java/uk/gov/hmcts/ccd/sdk/FPLConfigGenerationTests.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/enums/UserRole.java
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseType.json
ccd-sdk-types/src/main/java/uk/gov/hmcts/ccd/sdk/types/HasRole.java

Generate AuthorisationCaseType

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/CaseEventToFieldsGenerator.java

Remove hardcoded case type ID and replace with one from the config builder.

Add correct case type to case event fields generator

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/CaseFieldGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/FixedListGenerator.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/model/CaseData.java
ccd-config-generator/src/test/resources/ccd-definition/CaseField.json

Dont generate enums that have generate set to false

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/FieldCollection.java
ccd-config-generator/src/test/resources/ccd-definition/CaseEventToFields/addFamilyManCaseNumber.json
ccd-config-generator/src/test/resources/ccd-definition/CaseEventToFields/addNotes.json
ccd-config-generator/src/test/resources/ccd-definition/CaseEventToFields/openCase.json
ccd-config-generator/src/test/resources/ccd-definition/CaseEventToFields/populateSDO.json
config/checkstyle/checkstyle.xml

Add builder methods to FieldCollectionBuilder to simplify building.

Add build methods to field collection builder

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/CaseRoleGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigBuilderImpl.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/BaseCCDConfig.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/CaseRole.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/ConfigBuilder.java
ccd-config-generator/src/test/java/uk/gov/hmcts/ccd/sdk/FPLConfigGenerationTests.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-config-generator/src/test/resources/ccd-definition/CaseRoles.json

Add CaseRoles to builder and generator

Add CaseRoles to builder and generator

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/CaseRole.java

Add equals and hashcode to CaseRole class

Add equals and hashcode to CaseRole class

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/AuthorisationCaseFieldGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/Access.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/CCD.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/HasAccessControl.java
ccd-config-generator/src/test/java/uk/gov/hmcts/ccd/sdk/FPLConfigGenerationTests.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/access/BulkScan.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/model/CaseData.java
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-bulkscan.json
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-bulkscansystemupdate.json

Allow specification of field level access control on CaseData

Add field level access control

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/AuthorisationCaseFieldGenerator.java

Merge field level access control with event permissions (rather than overriding)

merge field level access

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/FieldType.java

- Need to define a new collection of documents type in case api which needs CCD Collection Field type.

Added Collection field type

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/AuthorisationCaseFieldGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/Permission.java

Allow CR perrmissions for labels so that they display in UI

Allow CR permissions for labels to display in UI

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/FieldCollection.java

Add method to create complex field with a show condition to the builder

Add complex field with show condition option to builder

---

build.gradle
ccd-config-generator/build.gradle
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/FieldType.java
ccd-gradle-plugin/build.gradle
jitpack.yml

- Tested publishing of artefact on Jitpack https://jitpack.io/#hmcts/ccd-config-generator/68d42e3c00 with case api

Remove bintray reference and fix jitpack publish

---

build.gradle

Refer https://jitpack.io/docs/BUILDING/

Use VERSION env var for jitpack

---

build.gradle

Reverts hmcts/ccd-config-generator#106

Revert "Use VERSION env var for jitpack"

---

.github/workflows/gradle.yml
build.gradle
ccd-config-generator/build.gradle
ccd-gradle-plugin/src/main/java/uk/gov/hmcts/ccd/sdk/CcdSdkPlugin.java

Remove remaining references to bintray and use jitpack coordinates for referencing the config generator jar

Use jitpack for publishing config generator jar

---

build.gradle
ccd-config-generator/build.gradle

Fix jitpack publish

---

build.gradle
ccd-config-generator/build.gradle
ccd-gradle-plugin/build.gradle

Set version for plugin and lib

---

ccd-gradle-plugin/build.gradle

fix plugin group for publishing

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/Main.java

Dont use spring DI during config generation

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/OrganisationPolicy.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/PreviousOrganisation.java

Add an undocumented field to OrganisationPolicy

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/CaseEventToFieldsGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigBuilderImpl.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ResolvedCCDConfig.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/ConfigBuilder.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/Event.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/Field.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/FieldCollection.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/runtime/CallbackController.java
ccd-config-generator/src/test/java/uk/gov/hmcts/ccd/sdk/CallbackControllerTest.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/event/AddCaseNumber.java
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-cafcass.json
ccd-config-generator/src/test/resources/ccd-definition/CaseEventToFields/addFamilyManCaseNumber.json
ccd-config-generator/src/test/resources/ccd-definition/CaseEventToFields/allocatedJudge.json
ccd-config-generator/src/test/resources/ccd-definition/CaseEventToFields/populateSDO.json

Since events can have callbacks per-page

Move midevent callback definition to page level

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/CaseDetails.java

Add builder for CaseDetails

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/FieldCollection.java

Call to complex method in FieldCollection was causing a stack overflow
Fixed and removed unused complex method

Fix complex method stack overflow in FieldCollection

---

build.gradle
ccd-config-generator/build.gradle
ccd-gradle-plugin/build.gradle
ccd-gradle-plugin/src/main/groovy/uk/gov/hmcts/ccd/sdk/CcdSdkPlugin.java

Since IDEs expect immutable maven artifacts.

Restore version numbers for config generator jar

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/PreviousOrganisation.java

Set the correct Json format for CCD for LocalDateTime in PreviousOrganisation

Set LocalDateTime correct Json format for CCD

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/Address.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/AddressGlobal.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/AddressGlobalUK.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/AddressUK.java

Add address complex types

---

.github/release-drafter.yml

add drafter config

---

.github/release-drafter.yml

Add draft config

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

add workflow

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/CaseEventToFieldsGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/Field.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/FieldCollection.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-solicitor.json
ccd-config-generator/src/test/resources/ccd-definition/CaseEventToFields/allocatedJudge.json

Add support for CaseEventFieldLabel and CaseEventFieldHint

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/CaseTypeTabGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/Tab.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/TabField.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-config-generator/src/test/resources/ccd-definition/CaseTypeTab/3_DraftOrdersTab.json

Add support for tab field DisplayContextParameter

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/CaseEventToComplexTypesGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/FieldCollection.java
ccd-config-generator/src/test/java/uk/gov/hmcts/ccd/sdk/FPLConfigGenerationTests.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-config-generator/src/test/resources/ccd-definition/CaseEventToComplexTypes/allocatedJudge/organisationPolicy.json
ccd-config-generator/src/test/resources/ccd-definition/CaseEventToFields/allocatedJudge.json

Add hints and labels for complex type fields

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/FieldCollection.java

Fix page field ordering with unwrapped complex types

Fix field ordering with unwrapped complex types

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/AuthorisationCaseFieldGenerator.java
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-solicitor.json

Fix field authorisation overwriting
Field authorisation was being overwritten depending on which event was processed first

Fix field authorisation overwriting

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/FieldCollection.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-cafcass.json
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-courtadmin.json
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-solicitor.json
ccd-config-generator/src/test/resources/ccd-definition/CaseEventToFields/addNotes.json
ccd-config-generator/src/test/resources/ccd-definition/CaseEventToFields/allocatedJudge.json
ccd-config-generator/src/test/resources/ccd-definition/CaseField.json

Fix an issue where labels inside unwrapped complex types are not added to the CaseField.json. 
Update the test to include top level label fields and unwrapped labels.

Fix for unwrapped labels in complex types

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/AuthorisationCaseFieldGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/CaseFieldGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/FieldCollection.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/model/HearingPreferences.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/model/LocationPreferences.java
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-bulkscan.json
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-bulkscansystemupdate.json
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-cafcass.json
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-courtadmin.json
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-solicitor.json
ccd-config-generator/src/test/resources/ccd-definition/CaseEventToFields/addNotes.json
ccd-config-generator/src/test/resources/ccd-definition/CaseField.json

- Add support for nested unwrapped types
- Fix bug where fields in an unwrapped class were given additional permissions
- Fix bug where fields in an unwrapped class were not given default permissions from the parent

Add support for nested unwrapped types

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/CaseEventToComplexTypesGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/FieldCollection.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/model/HearingPreferences.java
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-courtadmin.json
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-solicitor.json
ccd-config-generator/src/test/resources/ccd-definition/CaseEventToComplexTypes/addNotes/hearingPreferencesOrganisationPolicy.json
ccd-config-generator/src/test/resources/ccd-definition/CaseEventToFields/addNotes.json
ccd-config-generator/src/test/resources/ccd-definition/CaseField.json

fix for nested event to complex types

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/AuthorisationCaseStateGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ResolvedCCDConfig.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/enums/State.java
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseState.json

Allow explicit state permissions to be set on the state object

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigBuilderImpl.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/SearchCasesResultFieldsGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/ConfigBuilder.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/SearchCases.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/SearchCasesResultField.java
ccd-config-generator/src/test/java/uk/gov/hmcts/ccd/sdk/FPLConfigGenerationTests.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-config-generator/src/test/resources/ccd-definition/SearchCasesResultFields/SearchCasesResultFields.json

Add support for SearchCasesResultFields tab

Add search cases result fields

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/SearchCasesResultFieldsGenerator.java
ccd-config-generator/src/test/resources/ccd-definition/SearchCasesResultFields/SearchCasesResultFields.json

update the live from date for the search cases fields

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/FieldCollection.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-config-generator/src/test/resources/ccd-definition/CaseEventToComplexTypes/allocatedJudge/organisationPolicy.json

NFDIV-953: Method to overwrite label's for mandatoryNoSummary field

NFDIV-953: Method to overwrite label's for mandatoryNoSummary field

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/FieldCollection.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/model/Judge.java
ccd-config-generator/src/test/resources/ccd-definition/CaseEventToComplexTypes/allocatedJudge/allocatedJudge.json

Adding optionalNoSummary field which overwrites label

NFDIV-953:Adding optionalNoSummary field which overwrites label

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/AuthorisationCaseFieldGenerator.java

stop capitalization of case authorization fields with empty prefix

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigBuilderImpl.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/ConfigBuilder.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-cafcass.json
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-courtadmin.json
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-solicitor.json
ccd-config-generator/src/test/resources/ccd-definition/CaseTypeTab/13_ConfidentialAddress.json

Method to configure tab with show condition

NFDIV-780: Method to configure tab with show condition

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/CaseTypeTabGenerator.java

Fix show conditions for tabs with multiple rows

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/Event.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEvent.json
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-solicitor.json
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseState.json

Allow HasAccessControl to grant access on events

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/FieldCollection.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-courtadmin.json
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-solicitor.json
ccd-config-generator/src/test/resources/ccd-definition/CaseEventToFields/addNotes.json

Added method optionalWithLabel

NFDIV-843: Added method optionalWithLabel

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigBuilderImpl.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ResolvedCCDConfig.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/ConfigBuilder.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/AuthorisationCaseFieldGenerator.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-systemupdate.json

To omit history tab for configured roles

NFDIV-895: To omit history tab for configured roles

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/OrganisationPolicy.java

Add Json annotation to fix OrganisationPolicy empty value error

Fix OrganisationPolicy empty value error

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/Search.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/SearchCases.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/WorkBasket.java
ccd-config-generator/src/test/resources/ccd-definition/SearchCasesResultFields/SearchCasesResultFields.json
ccd-config-generator/src/test/resources/ccd-definition/SearchInputFields.json
ccd-config-generator/src/test/resources/ccd-definition/WorkBasketInputFields.json

Rename case reference label to Case Number

Rename case reference label to Case Number

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/AuthorisationCaseFieldGenerator.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/BulkCaseConfig.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/event/AddCaseNumber.java

Derive field permission from ccd annotation if explicit grants is enabled

NFDIV-1275

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/ChangeOrganisationApprovalStatus.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/ChangeOrganisationRequest.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/access/NoticeOfChangeAccess.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/enums/UserRole.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/model/CaseData.java
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-approver.json
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-caa.json
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseType.json
ccd-config-generator/src/test/resources/ccd-definition/CaseField.json

Add support for [ChangeOrganisationRequest](https://tools.hmcts.net/confluence/display/RCCD/CCD+Supported+Field+Types#CCDSupportedFieldTypes-ccdTypeChangeOrganisationRequest)

Add complex type for ChangeOrganisationRequest

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/AuthorisationCaseFieldGenerator.java

Derive permissions from field access not event access

NFDIV-1383

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/CaseEventGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/CaseEventToFieldsGenerator.java
ccd-config-generator/src/test/resources/ccd-definition/CaseEvent/addFamilyManCaseNumber.json
ccd-config-generator/src/test/resources/ccd-definition/CaseEvent/openCase.json
ccd-config-generator/src/test/resources/ccd-definition/CaseEventToFields/addFamilyManCaseNumber.json
ccd-config-generator/src/test/resources/ccd-definition/CaseEventToFields/allocatedJudge.json
ccd-config-generator/src/test/resources/ccd-definition/CaseEventToFields/populateSDO.json

This serves no functional purpose but makes diagnosing issues in appinsights easier as the event ID is available in the URL.

Add event ID to callback url as parameter

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/Field.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/FieldCollection.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/AuthorisationCaseFieldGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/CaseEventToFieldsGenerator.java
ccd-config-generator/src/test/resources/ccd-definition/CaseEventToFields/addNotes.json
ccd-config-generator/src/test/resources/ccd-definition/CaseEventToFields/allocatedJudge.json

This reverts commit fd6ff1489a5ea56562813aafdf56932ccd7ec395.

Revert "Remove complex types from case event fields (#238)"

---

gradle/wrapper/gradle-wrapper.properties

upgrade gradle

---

ccd-config-generator/build.gradle
ccd-gradle-plugin/build.gradle
ccd-gradle-plugin/src/main/groovy/uk/gov/hmcts/ccd/sdk/CcdSdkPlugin.java

replace deprecated jcenter

---

ccd-config-generator/build.gradle

upgrade reflection-util to 2.12 with record support

upgrade reflection lib

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/ExceptionRecordScannedDocument.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/ScannedDocument.java

Fix date format - Removed date formats as ISO 8601 is default format

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/CaseFieldGenerator.java
ccd-config-generator/src/test/resources/ccd-definition/CaseField.json

Now there will always be a valid label

Add a valid default label

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/WorkBasket.java

Add last modified date method for Work Basket search and results

NFDIV-1540

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/Field.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/FieldCollection.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/CaseEventToFieldsGenerator.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-config-generator/src/test/resources/ccd-definition/CaseEventToFields/addNotes.json

https://tools.hmcts.net/jira/browse/NFDIV-1721
Added Retain Hidden Value flag to the config

NFDIV-1721 : Added retain hidden value flag to the config

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/SearchField.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/WorkBasketField.java

This introduces some unsafe usage of Search and WorkBasket as the generic info is missing. Ideally we'd fix this but it would be quite disruptive.

Consolidate SearchInputField and WorkBasketInputField

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/FieldCollection.java

Added readonlyWithLabel to use readonly fields with custom label

NFDIV-1798 : added readonlyWithLabel

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/FieldCollection.java

Changed summary option to false

NFDIV-1798 : Corrected summary option

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigBuilderImpl.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/EventTypeBuilder.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/AuthorisationCaseStateGenerator.java
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseState.json

Add forStates overload, add permissions based on .forAllStates again

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/BulkScanEventTypeBuilderImpl.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigBuilderImpl.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/EventTypeBuilderImpl.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/BulkScanEventTypeBuilder.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/ConfigBuilder.java

Consolidate bulk scan event builders

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/AuthorisationCaseStateGenerator.java
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseState.json

dont grant state access to history only permissions

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigBuilderImpl.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ResolvedCCDConfig.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/ConfigBuilder.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/AuthorisationCaseTypeGenerator.java

Add ability to shutter service

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/Search.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/SearchField.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/SortOrder.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/SearchFieldAndResultGenerator.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-config-generator/src/test/resources/ccd-definition/WorkBasketResultFields.json
config/checkstyle/checkstyle.xml

Add the ability to order workbasket and search result lists

Add search results ordering

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigBuilderImpl.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ResolvedCCDConfig.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/ConfigBuilder.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/AuthorisationCaseTypeGenerator.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseType.json

Add shutter for specific roles

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/CaseTypeTabGenerator.java
ccd-config-generator/src/test/resources/ccd-definition/CaseTypeTab/12_PaymentHistory.json

Remove payments role from payments history tab

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigBuilderImpl.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/ConfigBuilder.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/CaseFieldGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/FieldType.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/model/CaseData.java

Remove automatic payment history tab creation

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/ScannedDocument.java

Models inside of an unwrapped type need an explicit constructor

Add json creator for scanned documents

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/AuthorisationCaseFieldGenerator.java

Recursively pass down the CCD access to nested unwrapped types.

Fix nested unwrapped access

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/JsonUtils.java

So we get exactly the same json output for a given configuration input.
This allows Gradle to skip converting it to xlsx if unchanged (eg. if we only changed a callback).

Emit deterministic JSON 

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/JsonUtils.java

Fix regression of JSON formatting

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/FieldType.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/model/CaseData.java
ccd-config-generator/src/test/resources/ccd-definition/CaseField.json

As per title, DynamicRadioList has been added as a field type.

Add DynamicRadioList as a field type to be used to override the dynamic list dropdown changing it to the radio list

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/FixedListGenerator.java
ccd-config-generator/src/test/java/uk/gov/hmcts/ccd/sdk/FPLConfigGenerationTests.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/enums/ChildGender.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/model/CaseData.java
ccd-config-generator/src/test/resources/ccd-definition/CaseField.json
ccd-config-generator/src/test/resources/ccd-definition/FixedLists/ChildGender.json

Use the name or label on the CCD annotation to generate the ListElement if the enum does not implement HasLabel

Use label from CCD annotation on fixed lists

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/ScannedDocument.java

Reverts hmcts/ccd-config-generator#300

Revert "Fix date format for scanned and delivery date"

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/ScannedDocument.java

Tested the change on demo refer PR https://github.com/hmcts/nfdiv-case-api/pull/1813/files

Update date formats for scanned and delivery dates

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/Field.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/FieldCollection.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/Search.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/SearchField.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/CaseEventToFieldsGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/SearchFieldAndResultGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/CaseLink.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-systemupdate.json
ccd-config-generator/src/test/resources/ccd-definition/CaseEventToFields/attachScannedDocs.json
ccd-config-generator/src/test/resources/ccd-definition/WorkBasketInputFields.json
ccd-config-generator/src/test/resources/ccd-definition/WorkBasketResultFields.json

https://tools.hmcts.net/jira/browse/DTSSE-2148

Add support for DisplayContextParameter on tabs and events

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/FieldType.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/FlagDetail.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/FlagLauncher.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/FlagType.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/Flags.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/model/CaseData.java
ccd-config-generator/src/test/resources/ccd-definition/CaseField.json

Types added for case flags

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/ComplexTypeGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/JsonUtils.java
ccd-config-generator/src/test/java/uk/gov/hmcts/ccd/sdk/FPLConfigGenerationTests.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/model/HearingBooking.java

Fixes complex fields being ordered alphabetically

Respect display order in complex types

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/WaysToPay.java

https://tools.hmcts.net/jira/browse/ADOP-1727

ADOP-1727 added WaysToPay ccd field type as part of config generator

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/WaysToPay.java

…d in casedata
added JsonIgnoreType annotation for **WaysToPay** as it is not a type that directly used in casedata

added JsonIgnoreType annotation for waystopay as it is not a type that directly used in casedata

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigResolver.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/runtime/CallbackController.java
ccd-config-generator/src/test/java/uk/gov/hmcts/ccd/sdk/FPLConfigGenerationTests.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/DerivedCaseData.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/DerivedCaseType.java
ccd-config-generator/src/test/resources/ccd-definition/FixedLists/PartyType.json

Add support for a hierarchy of CaseData classes

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/CaseTypeTabGenerator.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-cafcass.json
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-courtadmin.json
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-solicitor.json
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-systemupdate.json
ccd-config-generator/src/test/resources/ccd-definition/CaseField.json
ccd-config-generator/src/test/resources/ccd-definition/CaseTypeTab/2_DraftOrdersTab.json
ccd-gradle-plugin/build.gradle

A non functional change, only adding tests.

Expand tests to cover labels in tabs

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/Permission.java
ccd-gradle-plugin/test-projects/java-library/build.gradle
ccd-gradle-plugin/test-projects/java-library/src/main/java/uk/gov/hmcts/test/library/CCDConfig.java

remove guava from api

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/callback/AboutToStartOrSubmitResponse.java
ccd-config-generator/src/test/java/uk/gov/hmcts/ccd/sdk/CallbackControllerTest.java
ccd-config-generator/src/test/java/uk/gov/hmcts/ccd/sdk/model/AboutToStartOrSubmitCallbackResponse.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/event/SetSecurityClassification.java
ccd-config-generator/src/test/resources/CARE_SUPERVISION_EPO/AuthorisationCaseEvent/AuthorisationCaseEvent.json
ccd-config-generator/src/test/resources/CARE_SUPERVISION_EPO/CaseEvent/setDataAndSecurityClassification.json
ccd-config-generator/src/test/resources/CARE_SUPERVISION_EPO/CaseEvent/setSecurityClassification.json

Sptribs has a requirement to allow caseworkers
with certain roles to change the security
classification of cases.

ST-1086 Add security classification field

---

README.md
ccd-gradle-plugin/src/functionalTest/java/uk/gov/hmcts/ccd/sdk/FunctionalTest.java
ccd-gradle-plugin/src/main/groovy/uk/gov/hmcts/ccd/sdk/CcdSdkPlugin.java

support gradle 8, make gradle 7 minimum supported

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/Document.java

Caused by https://github.com/hmcts/dtsse-ccd-config-generator/pull/392/files

Fix breaking change to Document constructor

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/DynamicMultiSelectList.java

https://tools.hmcts.net/jira/browse/ST-645

ST-645 DynamicMultiSelectList object created

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/Event.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/CaseEventGenerator.java
ccd-config-generator/src/test/java/uk/gov/hmcts/ccd/sdk/E2EConfigGenerationTests.java
ccd-config-generator/src/test/resources/CARE_SUPERVISION_EPO/CaseEvent/addFamilyManCaseNumber.json
ccd-config-generator/src/test/resources/CARE_SUPERVISION_EPO/CaseEvent/addNotes.json
ccd-config-generator/src/test/resources/CARE_SUPERVISION_EPO/CaseEvent/allocatedJudge.json
ccd-config-generator/src/test/resources/CARE_SUPERVISION_EPO/CaseEvent/attachScannedDocs.json
ccd-config-generator/src/test/resources/CARE_SUPERVISION_EPO/CaseEvent/checkReady.json
ccd-config-generator/src/test/resources/CARE_SUPERVISION_EPO/CaseEvent/deleted.json
ccd-config-generator/src/test/resources/CARE_SUPERVISION_EPO/CaseEvent/handleEvidence.json
ccd-config-generator/src/test/resources/CARE_SUPERVISION_EPO/CaseEvent/openCase.json
ccd-config-generator/src/test/resources/CARE_SUPERVISION_EPO/CaseEvent/populateSDO.json
ccd-config-generator/src/test/resources/CARE_SUPERVISION_EPO/CaseEvent/setDataAndSecurityClassification.json

ST-1437 - Added publish flag in Event, for WA configuration in Special Tribunals

ST-1437 -Added publish flag in Event, for WA configuration in Special Tribunals

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/ComplexTypeGenerator.java

Document complex type generator

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/CaseLink.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/FieldType.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/LinkReason.java
ccd-config-generator/src/test/resources/CARE_SUPERVISION_EPO/ComplexTypes/2_LinkReason.json

Link type change and reason added

ST-475 Link type changes

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/FlagDetail.java

https://tools.hmcts.net/jira/browse/ST-1048

ST-1048 FlagDetail change

---

.github/renovate.json
renovate.json

Move and update renovate.json to .github directory.

Move and update renovate.json

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/FlagDetail.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/FlagLauncher.java

Changes required for Case Flags functionality as part of Sptribs module

ST-1048: Changes required for Case Flags functionality

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/CaseLink.java

Fixed issue with date field in Case Linking feature

ST-1051: Fixed issue with date field in Case Linking feature

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/SearchCriteria.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/SearchParty.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/model/CaseData.java
ccd-config-generator/src/test/resources/CARE_SUPERVISION_EPO/CaseField.json

Created two classes called SearchParty and SearchCriteria for global search to be enabled for work allocation to be seen by other services.
Jira :  https://tools.hmcts.net/jira/browse/ST-1248

ST-1248_Global_Search_CCD_Config

---

README.md

Document further customisation techniques

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/ChangeOrganisationRequest.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/model/CaseData.java

Reverts hmcts/dtsse-ccd-config-generator#469

Revert "[NFDIV-3945] Adjust CaseRoleID type for consistency with AAC API"

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigBuilderImpl.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ResolvedCCDConfig.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/ConfigBuilder.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/SearchCriteria.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/SearchParty.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/SearchCriteriaGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/SearchPartyGenerator.java
ccd-config-generator/src/test/java/uk/gov/hmcts/ccd/sdk/E2EConfigGenerationTests.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-config-generator/src/test/resources/CARE_SUPERVISION_EPO/SearchCriteria.json
ccd-config-generator/src/test/resources/CARE_SUPERVISION_EPO/SearchParty.json

Add config for search criteria and search party tabs in ccd definition
JIRA: https://tools.hmcts.net/jira/browse/DTSSTCI-178

DTSSTCI-178

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/SearchCriteria.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/SearchParty.java
ccd-config-generator/src/test/resources/CARE_SUPERVISION_EPO/CaseField.json

Update SearchCriteria and SearchParty complex type name to a single word as per standard

Updated SearchCriteria and SearchParty complex types

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/PreviousOrganisation.java
ccd-config-generator/src/test/resources/expected/response-notice-of-change-applied.json

NFDIV-3945: Make fields consistant with AAC service

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/CaseLocation.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/FieldType.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/SearchCriteria.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/SearchParty.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/model/CaseData.java
ccd-config-generator/src/test/resources/CARE_SUPERVISION_EPO/CaseField.json

To support global search configuration, added CCD CaseLocation complex type
https://tools.hmcts.net/jira/browse/DTSSTCI-178

Added CCD CaseLocation complex type

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/SearchParty.java

Updated SearchParty type to include collectionFieldName
https://tools.hmcts.net/jira/browse/DTSSTCI-178

Updated SearchParty type to include collectionFieldName

---

.github/workflows/stale.yml

DTSSE-5078 Add stale bot

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/FlagVisibility.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/Flags.java

https://tools.hmcts.net/jira/browse/NFDIV-4343
Change required to Flags.java to support Caseflags 2.1 for NFD service

NFDIV-4343 - Changes to support Caseflags2.1 for NFD service

---

build.gradle
ccd-config-generator/build.gradle
ccd-gradle-plugin/build.gradle
gradle/wrapper/gradle-wrapper.properties

upgrade to gradle 8

---

jitpack.yml

disable jitpack builds

---

ccd-config-generator/build.gradle
ccd-gradle-plugin/build.gradle
ccd-gradle-plugin/src/main/groovy/uk/gov/hmcts/ccd/sdk/CcdSdkPlugin.java

swap to az artifacts dependency repository

---

build.gradle
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/CaseEventGenerator.java
config/checkstyle/checkstyle.xml

upgrade checkstyle

---

sdk/ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/Main.java

fix generateCCDConfig

---

AGENTS.md
build.gradle
sdk/decentralised-runtime/src/main/java/uk/gov/hmcts/ccd/sdk/CaseController.java
sdk/decentralised-runtime/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigGeneratorCallbackDispatcher.java
test-projects/e2e/build.gradle
test-projects/e2e/src/cftlibTest/java/uk/gov/hmcts/divorce/cftlib/TestWithCCD.java
test-projects/e2e/src/main/java/uk/gov/hmcts/divorce/sow014/nfd/SubmittedConfirmationCallback.java

Ensure headers are propagated back to ccd

Fix submitted callback header propagation under decentralisation

---

test-projects/e2e/build.gradle
test-projects/e2e/src/cftlib/java/uk/gov/hmcts/divorce/cftlib/CftLibConfig.java
test-projects/e2e/src/cftlibTest/java/uk/gov/hmcts/divorce/cftlib/TestWithCCD.java
test-projects/e2e/src/main/java/uk/gov/hmcts/divorce/divorcecase/NoFaultDivorce.java
test-projects/e2e/src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java
test-projects/e2e/src/main/java/uk/gov/hmcts/divorce/divorcecase/model/access/CaseworkerCaseLinkAccess.java
test-projects/e2e/src/main/java/uk/gov/hmcts/divorce/sow014/nfd/CaseworkerAddNote.java
test-projects/e2e/src/main/java/uk/gov/hmcts/divorce/sow014/nfd/CaseworkerMaintainCaseLink.java

add tests for case linking
