hmcts/dtsse-ccd-config-generator

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigGenerator.java
ccd-config-generator/src/test/java/uk/gov/hmcts/ccd/sdk/FPLConfigGenerationTests.java

Clear output dir on every run to avoid orphaned files

Clear output dir on every run to avoid orphaned files

---

ccd-gradle-plugin/src/main/groovy/uk/gov/hmcts/ccd/sdk/CcdSdkPlugin.java

Fixes intellij project import by ensuring the config generator repository is always present for use by non-compilation tasks; config generator is now extracted in Gradle's configuration phase.

Fix intellij project import

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/AuthorisationCaseFieldGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/AuthorisationCaseStateGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/CaseEventGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/CaseEventToComplexTypesGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/CaseEventToFieldsGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigBuilderImpl.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/ConfigBuilder.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/Event.java

Remove features now supported natively by CCD around events; events now have a single 'id' field.

Further trimming of obsolete functionality

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/MoneyGBP.java

Add toInt method to mask the fact that money is stored as a String.

Money as int

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/Main.java

- Reverts hmcts/ccd-config-generator#114
- Reverting this as we need to load spring context for mid event callback.

Revert "Dont use spring DI during config generation"

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/AuthorisationCaseFieldGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/AuthorisationCaseStateGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigBuilderImpl.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/ConfigBuilder.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseState.json

ConfigBuilder.grant(State...) will now determine only AuthorisationCaseState and not cascade permissions to all events in the state.
Also removes some other unused permissions related functionality.

Remove inheritance of event permissions from states

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/FieldCollection.java

Fix unwrapped complex type PageID always set to 1 and appears on seperate page in event.

Fix unwrapped complex type page id always set to 1

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/CaseRoleGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/StateGenerator.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/enums/State.java
ccd-config-generator/src/test/resources/ccd-definition/State.json

Re-purpose the `@CCD` annotations label field to be used as the TitleDisplay for states. This means that the Name and Description of the state are always set to the value of the name field.

Add support for state TitleDisplay

---

ccd-config-generator/build.gradle

The config generator only needs the types defined in the ccd client library, not the spring runtime dependencies.
This will fix the build failure for spring boot 2.5, which was caused by incompatibilities with the ccd transitive dependencies.

Disable transitive dependency resolution for ccd client library

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigBuilderImpl.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigResolver.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ResolvedCCDConfig.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/Event.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/AuthorisationCaseEventGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/AuthorisationCaseFieldGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/AuthorisationCaseStateGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/AuthorisationCaseTypeGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/CaseEventGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/CaseEventToComplexTypesGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/CaseEventToFieldsGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/CaseFieldGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/CaseRoleGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/CaseTypeTabGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/ComplexTypeGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/FixedListGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/JSONConfigGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/SearchCasesResultFieldsGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/SearchFieldAndResultGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/StateGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/WorkBasketGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/runtime/CallbackController.java
ccd-config-generator/src/test/java/uk/gov/hmcts/ccd/sdk/CallbackControllerTest.java

Moves fields from ConfigBuilderImpl onto ResolvedCCDConfiguration and makes ConfigBuilderImpl package private.
Removed top level webhooks from ResolvedCCDConfiguration since they are already duplicated in the events.

Remove ConfigBuilderImpl from ResolvedCCDConfig

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigBuilderImpl.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/Tab.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/CaseEventGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/CaseTypeTabGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/GeneratorUtils.java
ccd-config-generator/src/test/java/uk/gov/hmcts/ccd/sdk/generator/GeneratorUtilsTest.java

If there is no display order set then use alphabetical name ordering for display order of events
Make ConfigBuilderImpl class public, so that current tests do not break in NFD
Rename Tab api class method to label(String fieldName, String showCondition, String label) as it creates a field of label type

Set event display order to alphabetical by name

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/Event.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/CaseEventGenerator.java

https://tools.hmcts.net/jira/browse/NFDIV-1097
Set ShowEventNotes to default to "N", to remove event summary and description entries on summary page.
Remove showSummaryChangeOption as CCD fails to load config if set.

Default ShowEventNotes as No, to remove event summary and description

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigBuilderImpl.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ResolvedCCDConfig.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/ConfigBuilder.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/runtime/CallbackController.java
ccd-config-generator/src/test/java/uk/gov/hmcts/ccd/sdk/CallbackControllerTest.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/RetiredFields.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/event/AddCaseNumber.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/model/CaseData.java

This change allows pre-event hooks to be added that can process the raw JSON before it's deserialized into the CaseData class. The example use case is to migrate data from old fields into new ones.

Add pre event hook to allow pre-processing of requests

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/CCD.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/FieldCollection.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/CaseFieldGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/ComplexTypeGenerator.java
ccd-config-generator/src/test/java/uk/gov/hmcts/ccd/sdk/generator/CaseFieldGeneratorTest.java
ccd-config-generator/src/test/java/uk/gov/hmcts/ccd/sdk/generator/ComplexTypeGeneratorTest.java

Add a displayOrder field to the CCD interface for complexFieldTypes
This allows control over the display order of the fields within the complexType when the complexType is added to a tab.

Allow list display order

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/Field.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/FieldCollection.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/AuthorisationCaseFieldGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/CaseEventToFieldsGenerator.java
ccd-config-generator/src/test/resources/ccd-definition/CaseEventToFields/addNotes.json
ccd-config-generator/src/test/resources/ccd-definition/CaseEventToFields/allocatedJudge.json

This change removes complex types from the CaseEventsToFields tab. Previously it was in with a DisplayContext of COMPLEX which is not a valid value. This change does still generate permissions for the complex type if it's used in an event

Remove complex types from case event fields

---

ccd-config-generator/src/main/resources/META-INF/spring.factories

We don't need these factories and can instead rely on component scanning.

Remove unnecessary spring factories

---

ccd-gradle-plugin/src/functionalTest/java/uk/gov/hmcts/ccd/sdk/FunctionalTest.java
ccd-gradle-plugin/src/main/groovy/uk/gov/hmcts/ccd/sdk/CcdSdkPlugin.java

Makes it possible for Gradle to skip running generateCCDConfig if it doesn't need to.

Use Gradle's up-to-date checking

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/CaseTypeTabGenerator.java
ccd-config-generator/src/test/resources/ccd-definition/CaseTypeTab/12_PaymentHistorypayments.json

If you don't have the payments role the tab will be empty

Make the payment history tab only for users with payment role

---

ccd-config-generator/src/main/resources/META-INF/spring-devtools.properties

Allows the config generator to be used with spring boot devtools for live reloading by ensuring the config generator is itself live reloaded.
See https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using.devtools.restart.customizing-the-classload

Spring boot devtools support

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/CCD.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/AuthorisationCaseFieldGenerator.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/model/HearingPreferences.java
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-bulkscan.json
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-bulkscansystemupdate.json
ccd-config-generator/src/test/resources/ccd-definition/AuthorisationCaseField/caseworker-publiclaw-solicitor.json

**This is a breaking change.**
Access control classes specified on unwrapped properties will now supplement the existing access control classes rather than replacing them. To revert to the old behaviour use the `inheritAccessFromParent` property on the `@CCD` annotation:
```
@CCD (
access = {},
inheritAccessFromParent = false
)
```

Add option to specify inheritance model of access control

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/deserializer/LocalDateTimeDeserializer.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/ScannedDocument.java

- We always received scanned date and delivery date with milliseconds consisting of 3 digits as bulk scan won’t allow less than 3 or more than 3 digits.
- But when milliseconds ends in something like 110 or 220 then looks like bulkscan service trims ending 0 when sending data to CCD.
- So for e.g if scanned date is `2022-04-27T11:25:46.420` then it is persisted as `2022-04-27T11:25:46.42`
- This then results in date format exception when we trigger callback in case api.

Use deserializer to format milliseconds in case ending zeros are removed while persisting in CCD

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/deserializer/LocalDateTimeDeserializer.java
ccd-config-generator/src/test/java/uk/gov/hmcts/ccd/sdk/deserializer/LocalDateTimeDeserializerTest.java

- make milliseconds optional when parsing dateTime
- https://tools.hmcts.net/jira/browse/NFDIV-2329

nfdiv-2329: make milliseconds optional when parsing dateTime

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/CCD.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/CaseRoleGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/FixedListGenerator.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/StateGenerator.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/enums/ChildGender.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/enums/State.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/enums/UserRole.java
ccd-config-generator/src/test/resources/ccd-definition/FixedLists/ChildGender.json

Remove the name property from the `@CCD` annotation to provide a more consistent API when using the `@CCD` configuration in different contexts. 
This is a breaking change.

Remove name property

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/JsonUtils.java

Since internal string encoding differs on windows.

Ensure json files are written as UTF-8

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/Document.java

added temporary ignore unknown annotation to Documents to avoid draft doc failing mid events with error "Unrecognized field **document_hash**"
https://tools.hmcts.net/jira/browse/NFDIV-2681

NFDIV-2681: added temporary ignore unknown annotation to avoid draft doc failing mid events

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ConfigBuilderImpl.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/ResolvedCCDConfig.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/CaseRoleToAccessProfile.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/ConfigBuilder.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/RoleToAccessProfilesGenerator.java
ccd-config-generator/src/test/java/uk/gov/hmcts/ccd/sdk/FPLConfigGenerationTests.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-config-generator/src/test/resources/ccd-definition/RoleToAccessProfiles.json

Add the CaseRoleToAccessProfiles tab: https://tools.hmcts.net/confluence/display/RCCD/CCD+Definition+Glossary+for+Setting+up+a+Service+in+CCD#CCDDefinitionGlossaryforSettingupaServiceinCCD-ccdDefTabRoleToAccessProfiles

Add case role to access profiles tab

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/ChangeOrganisationRequest.java

Adding a missing subfield to the definition (see [aac example of ChangeOrganisationRequest](https://github.com/hmcts/aac-manage-case-assignment/blob/9993c9a4712df5fa5523d189c31294b91b13e85c/src/main/java/uk/gov/hmcts/reform/managecase/domain/ChangeOrganisationRequest.java#L44)).

[NFDIV-3945] Add CreatedBy field to ChangeOrganisationRequest

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/SearchFieldAndResultGenerator.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/CCDConfig.java
ccd-config-generator/src/test/resources/CARE_SUPERVISION_EPO/AuthorisationCaseField/caseworker-publiclaw-courtadmin.json
ccd-config-generator/src/test/resources/CARE_SUPERVISION_EPO/AuthorisationCaseField/caseworker-publiclaw-solicitor.json
ccd-config-generator/src/test/resources/CARE_SUPERVISION_EPO/SearchInputFields.json
ccd-config-generator/src/test/resources/CARE_SUPERVISION_EPO/WorkBasketInputFields.json

https://tools.hmcts.net/jira/browse/NFDIV-2726
Search fields are merged based on CaseFieldID, meaning it's not possible to use the same search field for multiple roles (see example [CCD config in confluence](https://tools.hmcts.net/confluence/display/RCCD/Per-role+CaseTabs%2C+Workbasket+and+Search)). In this PR, we start merging search fields based on CaseFieldID and UserRole, meaning the same search field can be defined multiple times provided the role is unique.

[NFDIV-4461] Allow same search field to be used by different roles

---

build.gradle
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/FieldType.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/type/TTL.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/model/CaseData.java
ccd-config-generator/src/test/resources/CARE_SUPERVISION_EPO/CaseField.json

This change adds the new [TTL](https://tools.hmcts.net/confluence/display/RCCD/CCD+Supported+Field+Types#CCDSupportedFieldTypes-ccdTypeTTL) Complex Type for Java for use in [Retain & Dispose](https://tools.hmcts.net/confluence/pages/viewpage.action?pageId=1525469246#TechnicalSetupGuide:Retain&DisposeOnboardingConfiguration-Stepb:DefineTTLIncrementforsignificantevents).
Default behaviour: Leave the sub-fields blank as this means the case won't be deleted by Retain & Dispose.
Added to FPL CaseData to test.

[ADOP-2567] Added TTL Type

---

ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/CCD.java
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/CaseFieldGenerator.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/model/CaseData.java
ccd-config-generator/src/test/java/uk/gov/hmcts/reform/fpl/model/emergencyprotectionorder/EPOPhrase.java
ccd-config-generator/src/test/resources/CARE_SUPERVISION_EPO/CaseField.json
ccd-config-generator/src/test/resources/CARE_SUPERVISION_EPO/ComplexTypes/EPOPhrase.json

CCD allows configuration of a Searchable column to specify whether a case field will be indexed by Elastic Search:
https://tools.hmcts.net/confluence/pages/viewpage.action?spaceKey=RCCD&title=Configuring+Searchable+column
Case fields are searchable (indexed) by default. This PR adds support for configuration of searchable in the CCD annotation of a case field. Where searchable has been specified as false in the annotation, "Searchable": "N" will be set in the CCD config to indicate the field should not be indexed.
https://tools.hmcts.net/jira/browse/NFDIV-4775

[NFDIV-4775] Support configuration of Searchable

---

ccd-config-generator/build.gradle
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/generator/CaseEventToFieldsGenerator.java
ccd-config-generator/src/test/java/uk/gov/hmcts/ccd/sdk/E2EConfigGenerationTests.java
ccd-config-generator/src/test/resources/CARE_SUPERVISION_EPO/CaseEventToFields/attachScannedDocs.json
ccd-config-generator/src/test/resources/CARE_SUPERVISION_EPO/CaseEventToFields/handleEvidence.json

Assign the page label to all fields in an event page because the fields are sorted when written to the JSON but CCD uses the page label in the _first_ field of the serialised case definition, (not necessarily the order of the fields in the Java config).
This also means that if the config is generated a second time, (as done by the e2e tests), then the page labels will still be present.
This PR also removes commons-lang which has an unresolved CVE and switches the single use of it, (in the e2e tests), to use commons-lang3
See #554 for more details of the issue.

Fix missing event page labels (#554)

---

test-projects/e2e/src/cftlibTest/java/uk/gov/hmcts/divorce/cftlib/TestWithCCD.java

- exclude ServiceBusJmsAutoConfiguration for the cftlib TestWithCCD suite so Azure's starter does not demand a connection string
- ./gradlew e2e:cftlibTest

Exclude Azure Service Bus auto-config from cftlib test

---

test-projects/e2e/build.gradle
test-projects/e2e/src/cftlibTest/java/uk/gov/hmcts/divorce/cftlib/TestWithCCD.java

- replace the TestWithCCD gson calls with the existing ObjectMapper
- remove the redundant gson test dependency
- ./gradlew :e2e:cftlibTestClasses

chore(e2e): replace gson with jackson
